# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 14:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bathroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('building', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=4)),
                ('gender', models.CharField(max_length=8)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3)),
                ('bathroomSlug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BathroomInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True)),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Bathroom')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userSlug', models.SlugField(unique=True)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bathroominteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.UserProfile'),
        ),
    ]
